name: Fetch AQHI Data Hourly at :15

on:
  schedule:
    - cron: '15 * * * *'  # ⏰ Every hour at 15 minutes past (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          pak: true
          extra-packages: |
            any::httr
            any::jsonlite
            any::dplyr
            any::lubridate
            any::purrr
            any::readr
            any::fs

      - name: Run AQHI fetch script
        run: Rscript scripts/fetch_aqhi.R

      - name: Commit and push results
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/**/*.csv'
          message: 'AQHI data update at :15 past the hour'
          default_author: github_actions
